### ISSUE TITLE
[new rule] create rule for formatting prices

### ISSUE THREAD

**Issue by BirgitBader** [otto-de/api-guidelines#29]
_(i) This issue has been manually transferred from a former internal repository, as a private repository issue cannot be transferred to a public repository._

## Context

We currently have no rule defining the format of a money amount in an API.

As money amounts are very common in our APIs (checkout, order-positions, transactional-communication), we would like to introduce a rule that ensures that money amounts are always formatted the same.

Currently, a money amount is formatted as eurocents (integer) in the APIs checkout, order-positions, and transactional-communication.

**Comment by BirgitBader** [comment]
## Comment history

Feb 22, 2023 by @cfranzen

> Why not stick to the ISO standard for formatting currencies? (https://de.wikipedia.org/wiki/ISO_4217) Can we rely on euros as currency? I think Otto at least has some business in the UK and Switzerland.

Feb 22, 2023 by @thake 

> Thanks for your input @cfranzen! I think the checkout API was the first API that displayed money amounts. @jensfischer1515, can you give some background on why eurocents has been chosen?

**Comment by BirgitBader** [comment]
Feb 28, 2023 by @thake 

OrderEvent of kraken uses:
```json
{
  "price": {"amount": 10.34, "currency": "EUR"}
}

**Comment by BirgitBader** [comment]
Feb 28, 2023 by @thake

## Proposal
My proposed format after a discussion with @jensfischer1515, @JanKlasser3000, @BastianSperrhacke-Otto, and @sergey-kolodiev
### Example
```json
{
  "price": {"amount":  "1.45", "currency": "EUR" /* optional, defaults to EUR */}
}
```
### Schema
```yaml
title: Money
description: Common format for money amounts.
type: object
required:
  - amount
properties:
  amount:
    type: string
    description: The money amount without currency. "." is used as a decimal separator.
    pattern: ^\d+(\.\d+)?$
  currency:
    type: string
    description: The alphabetic currency code for the amount as defined in ISO 4217.
    enum:
      - "EUR"
    default: "EUR"
    pattern: "^[A-Z]{3}$"
```

### Reasoning

The object format has been used in preference to eurocents because of the following reasons:
- Although currently not needed, a clear separation of currency and money amount is possible.
- Easier to use in OpenAPI and AsyncAPI definitions because one does not need to repeat the description of the money amount every time it is used in a property.

`string` has been chosen as a type for `amount` because `number` is deserialized to an IEEE 754 float representation (see https://floating-point-gui.de/). The representation as float can lead to rounding and calculation errors. This is especially true for currencies with many decimal places (e.g., bitcoin). Example in javascript:
```javascript
let a = 2.2
let b = 2.1
console.log(a+b) //logs 4.300000000000001
```

`currency` is by default "EUR" and thus can be absent for most of OTTOs APIs. This reduces the payload for the current use cases.

## Remarks
All participants of today's meeting were fully aware that introducing a new currency will always be a breaking change. APIs and their clients need to make adaptions to handle a new currency.
